/*
 * Copyright (C) 2006  Antonie Struyk
 *
 * This file is part of Freetar Hero.
 *
 *    Freetar Hero is free software; you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation; either version 2 of the License, or
 *    (at your option) any later version.
 *
 *    Freetar Hero is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with Freetar Hero; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

package net.freetar.game.tests;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;

/**
 *
 * @author  Anton
 */
public class HUDPanel extends javax.swing.JPanel {
    
    /** Creates new form TestPanel */
    public HUDPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        multLabel = new javax.swing.JLabel();
        multText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        scoreLabel = new javax.swing.JLabel();
        scoreText = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        timeText = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        streakLabel = new javax.swing.JLabel();
        streakText = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 3));

        jPanel1.setOpaque(false);
        multLabel.setFont(new java.awt.Font("Impact", 1, 24));
        multLabel.setForeground(new java.awt.Color(255, 0, 0));
        multLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multLabel.setText("Mult");

        multText.setFont(new java.awt.Font("Courier New", 1, 18));
        multText.setForeground(new java.awt.Color(255, 255, 255));
        multText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multText.setText("0 x");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, multText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, multLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(multLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(multText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        add(jPanel1);

        jPanel3.setOpaque(false);
        scoreLabel.setFont(new java.awt.Font("Impact", 1, 36));
        scoreLabel.setForeground(new java.awt.Color(255, 0, 0));
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLabel.setText("SCORE");

        scoreText.setFont(new java.awt.Font("Courier New", 1, 18));
        scoreText.setForeground(new java.awt.Color(255, 255, 255));
        scoreText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreText.setText("000000000");

        timeLabel.setFont(new java.awt.Font("Impact", 0, 18));
        timeLabel.setForeground(new java.awt.Color(255, 0, 0));
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("Time");

        timeText.setFont(new java.awt.Font("Courier New", 1, 14));
        timeText.setForeground(new java.awt.Color(255, 255, 255));
        timeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeText.setText("0:00:00");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(scoreLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .add(timeText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, timeLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .add(scoreText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(scoreLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scoreText)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 221, Short.MAX_VALUE)
                .add(timeLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(timeText)
                .addContainerGap())
        );
        add(jPanel3);

        jPanel2.setOpaque(false);
        streakLabel.setFont(new java.awt.Font("Impact", 1, 24));
        streakLabel.setForeground(new java.awt.Color(255, 0, 0));
        streakLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        streakLabel.setText("Streak");

        streakText.setFont(new java.awt.Font("Courier New", 1, 18));
        streakText.setForeground(new java.awt.Color(255, 255, 255));
        streakText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        streakText.setText("0");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, streakText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, streakLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(streakLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(streakText)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        add(jPanel2);

    }// </editor-fold>//GEN-END:initComponents
    
    
    public void setScoreText(String text){
        scoreText.setText(text);
    }
    
    public void setStreakText(String text){
        streakText.setText(text);
    }
    
    public void setTimeText(String text){
        timeText.setText(text);
    }
    
    public void setMultText(String text){
        multText.setText(text);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel multLabel;
    private javax.swing.JLabel multText;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreText;
    private javax.swing.JLabel streakLabel;
    private javax.swing.JLabel streakText;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeText;
    // End of variables declaration//GEN-END:variables
    
}
